# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d580484b7226c5349df7f0e4079fd36cbf87b404c41fb121a5c5ca2d9d19c80e0bb8807205aafa56608b5516da7b018b5899ed98903b078602bc20ee725e0b

test:
  secret_key_base: 2f26edee67cf10e5cc228e4e1af22d3f0e168346f66a066adaae12a24286bbb91eab20f3a6edfd14c6dc32cce8aca33a79dfd5e786bba5de501c73a08c3ca00e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
